<a href="https://colab.research.google.com/github/elinteerie/Pytorch/blob/main/Pytorch_Training_Steps.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

###Load All Dependencies and Libraries

In [1]:
import numpy as np
from sklearn.linear_model import LinearRegression
import torch
import torch.optim as optim
import torch.nn as nn
from torch.utils.data import Dataset, TensorDataset, DataLoader
from torch.utils.data.dataset import random_split
from torch.utils.tensorboard import SummaryWriter
import matplotlib.pyplot as plt
%matplotlib inline
plt.style.use('fivethirtyeight')

In [22]:
## Set up Device Agnostic Code
device = 'cuda' if torch.cuda.is_available() else 'cpu'

In [23]:
### Set up synthetic Data
# Y = a + bX
weight = 4
bias = 6
X = torch.rand(100, 1)
y = (weight * X) +  bias

In [24]:
#Set Train data to device
X_train = torch.as_tensor(X).to(device)
y_train = torch.as_tensor(y).to(device)

In [26]:
#Preview some sample
X_train[1], y_train[1]

(tensor([0.2914]), tensor([7.1656]))

In [29]:
###Set up model
class CustomLinearModel(nn.Module):
  def __init__(self):
    super().__init__()
    self.linear = nn.Linear(in_features=1, out_features=1)

  def forward(self, x):
    return self.linear(x)

In [30]:
model = CustomLinearModel()

In [31]:
model.state_dict

<bound method Module.state_dict of CustomLinearModel(
  (linear): Linear(in_features=1, out_features=1, bias=True)
)>

In [34]:
list(model.parameters())

[Parameter containing:
 tensor([[0.9196]], requires_grad=True), Parameter containing:
 tensor([-0.5684], requires_grad=True)]

In [35]:
#Set up Loss Function and Optimizer
lossfn = nn.MSELoss(reduction ='mean')
optimizer = optim.SGD(model.parameters(), lr = 0.1)

In [41]:
###Model Training
%%writefile model_training/V0.py

# Defines Number of Epochs

n_epochs = 100

for epoch in range(n_epochs):
  model.train()

  y_pred = model(X_train)
  loss = lossfn(y_pred, y_train)
  loss.backward()
  optimizer.step()
  optimizer.zero_grad()
print(model.state_dict())


Writing model_training/V0.py


In [ ]:
def make_train_step(model, lossfn, optimizer):
  def perform_train_step(x,y):
    model.train()
    y_pred =model(x)
    loss = lossfn(y_pred, y)
    loss.backward()
    optimizer.step()
    optimizer.zero_grad()
    return loss.item()

  return perform_train_step